version: '3.8'

services:
  api:
    build:
      context: ./api
      target: prod
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DJANGO_SETTINGS_MODULE: quotes_tracker.settings.prod
    volumes:
      - ./api:/quotes_tracker
    ports:
      - "8000:8000"
    restart: always
  
  frontend:
    build:
      context: ./frontend
      target: prod
    restart: always
#    ports:
#      - "3000:3000"
#    volumes:
#      - ./frontend:/quotes_tracker

  reverse_proxy:
    build:
      context: ./nginx
      target: prod
    ports:
      - 81:80
    depends_on:
      - api
      - frontend
    restart: always