version: '3.8'

services:
  db:
    image: postgres:latest
    env_file:
      - ./api/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 120s
      timeout: 120s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  api:
    build:
      context: ./api
    env_file:
      - ./api/.env
    volumes:
      - ./api:/quotes_tracker
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/quotes_tracker
    
volumes:
  postgres_data:
