# Generated by Django 5.0.1 on 2024-01-18 18:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("16b31dfb-dd0f-473e-97c0-5c7e80db7d40"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
