# Generated by Django 5.0.1 on 2024-01-19 06:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker_app", "0003_alter_store_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
