# Generated by Django 5.0.1 on 2024-01-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker_app", "0004_alter_store_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="status",
            field=models.CharField(
                choices=[
                    ("need_to_send", "Need to Send Request"),
                    ("sent", "Request Sent"),
                    ("received", "Quote Received"),
                    ("need_to_resend", "Need to Resend Request"),
                    ("done", "Done"),
                ],
                default="need_to_send",
                max_length=50,
            ),
        ),
        migrations.DeleteModel(
            name="QuoteRequest",
        ),
    ]
