name: Continuous Integration Workflow with PyTest

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Create .env file
      run: |
        touch api/.env
        echo "DB_NAME=${{ secrets.DB_NAME }}" >> api/.env
        echo "DB_USER=${{ secrets.DB_USER }}" >> api/.env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> api/.env
        echo "DB_HOST=${{ secrets.DB_HOST }}" >> api/.env
        echo "DB_PORT=${{ secrets.DB_PORT }}" >> api/.env
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> api/.env
        cat api/.env

    - name: Build the Docker image
      env:
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: docker-compose build

    - name: Start the Docker containers
      env:
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: docker-compose up -d --wait && docker-compose ps && docker-compose logs api

    - name: Run tests in the Docker environment
      env:
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: docker-compose exec -T api pytest

