name: Continuous Integration Workflow with PyTest

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Create .env file
      run: |
        touch api/.env
        echo "DB_NAME=${{ secrets.DB_NAME }}" >> api/.env
        echo "DB_USER=${{ secrets.DB_USER }}" >> api/.env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> api/.env
        echo "DB_HOST=${{ secrets.DB_HOST }}" >> api/.env
        echo "DB_PORT=${{ secrets.DB_PORT }}" >> api/.env
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> api/.env
        cat api/.env

    - name: Build the Docker image
      run: docker-compose build

    - name: Start the Docker containers
      run: docker-compose up -d && docker-compose ps && docker-compose logs api

    - name: Run tests in the Docker environment
      run: docker-compose exec -T api pytest

